linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - prealloc
    - predeclared
    - revive
    - stylecheck
    - whitespace
