version: 2
before:
  hooks:
    - go mod tidy
builds:
  -
    main: ./cmd/gobrew
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: darwin
        goarch: arm
archives:
  -
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^bin'
      - '^Merge pull'
