name: "go-gobrew"
author: "kevincobain2000"
description: "gobrew, setup go for Github Actions"
branding:
  icon: 'heart'
  color: 'green'

inputs:
  version:
    description: "go version"
    required: true
runs:
  using: "composite"
  steps:
    - name: gobrew setup
      run: |
        echo "$HOME/.gobrew/current/bin" >> $GITHUB_PATH
        echo "$HOME/.gobrew/bin"  >> $GITHUB_PATH
        curl -sLk https://git.io/gobrew | sh -
      shell: bash

    - name: gobrew use
      run: gobrew use ${{ inputs.version }}
      shell: bash
