on:
  pull_request:
    paths:
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
      - '**/*.yml'

name: "Build"
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./cmd/gobrew
        shell: bash
