on:
  push:
    branches:
      - master
name: scc

jobs:
  scc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: kevincobain2000/action-scc@v1
